dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_joint_1
      - arm_joint_2

  # second_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: second

dynamixel_control_hw:
  serial_interface: /dev/ttyUSB0
  loop_frequency: 50
  cycle_time_error_threshold: 0.1
  baudrate: 1000000 # in bauds
  dynamixel_timeout: 0.05 # in seconds
  dynamixel_scanning: 0.05 # in seconds
  # correspondance between hardware IDs of the actuators and their names in ROS
  hardware_mapping:
    arm_joint_1: 3
    arm_joint_2: 1
  # offset to be added, in radians, to the position of an actuator
  hardware_corrections:
    "1": 3.14159265359
    "3": 3.14159265359
